# XORA application build inputs. Keep the established link order.
# New implementation files must be added explicitly; directory moves must not enable legacy code.

C_SOURCES := \
Core/Src/bdma.c \
Src/system/board.c \
Src/support/delay_timer.c \
Core/Src/dma.c \
Core/Src/gpio.c \
Core/Src/main.c \
Core/Src/stm32h7xx_hal_msp.c \
Core/Src/stm32h7xx_it.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/system_stm32h7xx.c \
Core/Src/tim.c \
Src/support/utils.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_qspi.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
Src/config/drivers/qspi/qspi-w25q64.c \
Src/system/drivers/usart/usart.c \
Src/input/drivers/adc/adc.c \
Src/power/drivers/power_i2c_bus/power_i2c_bus.c \
Src/power/drivers/bq25895/bq25895.c \
Src/power/drivers/max17048/max17048.c \
Src/leds/drivers/ws2812b/pwm-ws2812b.c \
Src/input/drivers/gpio/gpio-btn.c \
Src/input/drivers/rotary_encoder/rotary-encoder.c \
Src/display/drivers/st7789/spi-st7789-resume.c \
Src/display/drivers/st7789/spi-st7789.c \
Libs/cJSON/cJSON.c \
Libs/cJSON/cJSON_Utils.c \
Libs/sha256_simple/sha256_simple.c \
../common/boot_profile.c \
../common/device_identity_store.c \
../common/device_security_boot_context.c \
../common/device_security_crypto.c \
../common/firmware_signature.c \
../common/hardware_rng.c \
../common/physical_confirmation.c \
../common/security_version_journal.c \
../common/usb_board_link_codec.c \
Libs/mbedtls/library/bignum.c \
Libs/mbedtls/library/base64.c \
Libs/mbedtls/library/aes.c \
Libs/mbedtls/library/cipher.c \
Libs/mbedtls/library/cipher_wrap.c \
Libs/mbedtls/library/constant_time.c \
Libs/mbedtls/library/ecp.c \
Libs/mbedtls/library/ecp_curves.c \
Libs/mbedtls/library/ecdh.c \
Libs/mbedtls/library/ecdsa.c \
Libs/mbedtls/library/gcm.c \
Libs/mbedtls/library/hkdf.c \
Libs/mbedtls/library/md.c \
Libs/mbedtls/library/sha256.c \
Libs/mbedtls/library/platform_util.c

CPP_SOURCES := \
Src/system/board_mode.cpp \
Src/power/board_power.cpp \
Src/system/board_security_confirmation.cpp \
Src/firmware/ch585_firmware_update.cpp \
Src/firmware/ch585_iap_client.cpp \
Src/transport/ch585_role_bootstrap.cpp \
Src/config/config.cpp \
Src/webconfig/config_transport_sink.cpp \
Src/transport/connection_manager.cpp \
Src/system/cpp_main.cpp \
Src/support/cpp_utils.cpp \
Src/input/gamepad.cpp \
Src/input/hotkeys_manager.cpp \
Src/diagnostics/latency_monitor.cpp \
Src/system/main_state_machine.cpp \
Src/system/message_center.cpp \
Src/support/micro_timer.cpp \
Src/diagnostics/monitor_telemetry.cpp \
Src/power/power_manager.cpp \
Src/input/report_scheduler.cpp \
Src/transport/rf/rf_boot_ready.cpp \
Src/transport/rf/rf_bridge_port.cpp \
Src/transport/rf/rf_command_transaction.cpp \
Src/transport/rf/rf_reliable_event.cpp \
Src/transport/rf/rf_sleep_recovery.cpp \
Src/transport/rf/rf_transport.cpp \
Src/power/sleep_diagnostics.cpp \
Src/config/storagemanager.cpp \
Src/power/system_sleep_manager.cpp \
Src/power/system_stop.cpp \
Src/transport/usb/usb_board_link.cpp \
Src/transport/usb/usb_board_link_port.cpp \
Src/transport/usb/usbdriver.cpp \
Src/transport/usb/legacy/usbhostmanager.cpp \
Src/webconfig/webhid_rpc_dispatcher.cpp \
Src/webconfig/webhid_service.cpp \
Src/webconfig/configs/calibration_command_handler.cpp \
Src/webconfig/configs/common_command_handler.cpp \
Src/webconfig/configs/config_sync.cpp \
Src/webconfig/configs/device_command_handler.cpp \
Src/webconfig/configs/device_command_message.cpp \
Src/webconfig/configs/firmware_command_handler.cpp \
Src/webconfig/configs/global_config_command_handler.cpp \
Src/webconfig/configs/ms_mark_command_handler.cpp \
Src/webconfig/configs/profile_command_handler.cpp \
Src/webconfig/configs/rf_binding_command_handler.cpp \
Src/webconfig/configs/user_image_command_handler.cpp \
Src/webconfig/configs/webconfig_btns_manager.cpp \
Src/webconfig/configs/webconfig_leds_manager.cpp \
Src/input/gamepad/GamepadState.cpp \
Src/system/states/calibration_state.cpp \
Src/system/states/ch585_bridge_update_state.cpp \
Src/system/states/input_state.cpp \
Src/system/states/safe_recovery_state.cpp \
Src/system/states/webconfig_state.cpp \
Src/input/adc_btns/adc_btns_marker.cpp \
Src/input/adc_btns/adc_btns_worker.cpp \
Src/input/adc_btns/adc_calibration.cpp \
Src/input/adc_btns/adc_manager.cpp \
Src/input/adc_btns/ring_buffer_sliding_window.cpp \
Src/input/gpio_btns/gpio_btns_worker.cpp \
Src/leds/gradient_color.cpp \
Src/leds/led_animation.cpp \
Src/leds/led_strip_controller.cpp \
Src/leds/leds_manager.cpp \
Src/firmware/firmware_manager.cpp \
Src/display/screen_control/spi_screen_detail_ambient_brightness.cpp \
Src/display/screen_control/spi_screen_detail_ambient_effect.cpp \
Src/display/screen_control/spi_screen_detail_buttons_performance.cpp \
Src/display/screen_control/spi_screen_detail_calibration_mode.cpp \
Src/display/screen_control/spi_screen_detail_input_mode.cpp \
Src/display/screen_control/spi_screen_detail_light_brightness.cpp \
Src/display/screen_control/spi_screen_detail_light_effect.cpp \
Src/display/screen_control/spi_screen_detail_pages.cpp \
Src/display/screen_control/spi_screen_detail_profiles.cpp \
Src/display/screen_control/spi_screen_detail_render_helpers.cpp \
Src/display/screen_control/spi_screen_detail_screen_brightness.cpp \
Src/display/screen_control/spi_screen_detail_socd.cpp \
Src/display/screen_control/spi_screen_detail_tournament_mode.cpp \
Src/display/screen_control/spi_screen_detail_web_config.cpp \
Src/display/screen_control/spi_screen_main_list.cpp \
Src/display/screen_control/spi_screen_manager.cpp \
Src/display/screen_control/spi_screen_standby.cpp \
Src/display/screen_control/spi_screen_timed_popup.cpp \
Src/display/screen_control/spi_screen_ui_common.cpp \
Libs/CRC32/src/CRC32.cpp

APPLICATION_INCLUDE_DIRS := \
Inc \
Inc/system \
Inc/support \
Inc/input \
Inc/transport \
Inc/transport/rf \
Inc/transport/usb \
Inc/transport/usb/legacy \
Inc/config \
Inc/webconfig \
Inc/power \
Inc/display \
Inc/firmware \
Inc/diagnostics \
Inc/webconfig/configs \
Inc/transport/usb/legacy/drivers \
Inc/input/gamepad \
Inc/system/states \
Inc/leds \
Inc/display/screen_control \
Inc/config/drivers/qspi \
Inc/system/drivers/usart \
Inc/input/drivers/adc \
Inc/power/drivers/power_i2c_bus \
Inc/power/drivers/bq25895 \
Inc/power/drivers/max17048 \
Inc/leds/drivers/ws2812b \
Inc/input/drivers/gpio \
Inc/input/drivers/rotary_encoder \
Inc/display/drivers/st7789
