#include "platform_port.h"
#include "rfm_spi_port.h"

#include <stddef.h>

#include "CH58x_common.h"

/* SPI wiring with STM32 host: CS/PB12, SCK/PB13, MOSI/PB14, MISO/PB15, IRQ/PB11. */
#define SPI_PINS        (GPIO_Pin_12 | GPIO_Pin_13 | GPIO_Pin_14 | GPIO_Pin_15)
#define SPI_IRQ_PIN     (GPIO_Pin_11)

#define US_TICK_STEP      10u
#define TMR0_PERIOD_10US  (FREQ_SYS / 100000u)

static volatile uint32_t s_now_us;
static bool s_spi_tx_pending;
static uint32_t s_spi_tx_start_us;
/* Allow host enough time to start readback transaction after IRQ assertion. */
#define SPI_TX_PENDING_RECOVER_US 50000u
static uint8_t s_spi_tx_buf[96];
static uint16_t s_spi_tx_len;
static uint16_t s_spi_tx_pos;

static void spi_tx_fill_fifo(void)
{
    while ((s_spi_tx_pos < s_spi_tx_len) && (R8_SPI0_FIFO_COUNT < SPI_FIFO_SIZE)) {
        R8_SPI0_FIFO = s_spi_tx_buf[s_spi_tx_pos++];
    }
}

bool rfm_spi_port_try_read(uint8_t *buf, size_t *inout_len)
{
    size_t max_len;
    size_t n = 0u;
    size_t expected;
    uint32_t wait_deadline_us;

    if ((buf == 0) || (inout_len == 0)) {
        return false;
    }
    max_len = *inout_len;
    if (max_len < 4u) {
        return false;
    }
    if (s_spi_tx_pending) {
        spi_tx_fill_fifo();
        if ((R8_SPI0_INT_FLAG & RB_SPI_IF_CNT_END) == 0u) {
            /*
             * If host aborted/short-read previous response, recover after CS idle
             * timeout so command RX path doesn't get blocked forever.
             */
            if (GPIOB_ReadPortPin(GPIO_Pin_12) &&
                ((int32_t)(platform_now_us() - (s_spi_tx_start_us + SPI_TX_PENDING_RECOVER_US)) >= 0)) {
                s_spi_tx_pending = false;
                platform_irq_line_set(false);
                while (R8_SPI0_FIFO_COUNT != 0u) {
                    (void)R8_SPI0_FIFO;
                }
                R8_SPI0_CTRL_MOD |= RB_SPI_FIFO_DIR;
            } else {
                return false;
            }
        } else {
            R8_SPI0_INT_FLAG = RB_SPI_IF_CNT_END;
            s_spi_tx_pending = false;
        }
    }

    /* Keep slave in RX direction for command ingestion. */
    R8_SPI0_CTRL_MOD |= RB_SPI_FIFO_DIR;
    if (R8_SPI0_FIFO_COUNT == 0u) {
        return false;
    }

    /* Read fixed header first. */
    wait_deadline_us = platform_now_us() + 300u;
    while (n < 3u) {
        if (R8_SPI0_FIFO_COUNT != 0u) {
            buf[n++] = R8_SPI0_FIFO;
            wait_deadline_us = platform_now_us() + 300u;
            continue;
        }
        if ((int32_t)(platform_now_us() - wait_deadline_us) >= 0) {
            return false;
        }
    }

    expected = (size_t)(3u + buf[2] + 1u);
    if ((expected < 4u) || (expected > max_len)) {
        return false;
    }

    /* Read exactly one frame, ignore any tail bytes generated by follow-up clocks. */
    wait_deadline_us = platform_now_us() + 300u;
    while (n < expected) {
        if (R8_SPI0_FIFO_COUNT != 0u) {
            buf[n++] = R8_SPI0_FIFO;
            wait_deadline_us = platform_now_us() + 300u;
            continue;
        }
        if ((int32_t)(platform_now_us() - wait_deadline_us) >= 0) {
            return false;
        }
    }

    while (R8_SPI0_FIFO_COUNT != 0u) {
        (void)R8_SPI0_FIFO;
    }

    *inout_len = n;
    return true;
}

bool rfm_spi_port_try_write(const uint8_t *buf, size_t len)
{
    size_t i;
    if ((buf == 0) || (len == 0u)) {
        return false;
    }
    if (len > 4095u) {
        return false;
    }
    if (len > sizeof(s_spi_tx_buf)) {
        return false;
    }

    /* Switch SPI0 slave to TX direction and stage one full response frame. */
    R8_SPI0_CTRL_MOD &= (uint8_t)(~RB_SPI_FIFO_DIR);
    R16_SPI0_TOTAL_CNT = (uint16_t)len;
    R8_SPI0_INT_FLAG = RB_SPI_IF_CNT_END;

    /* Drain stale bytes if any to avoid shifted readback on next transaction. */
    while (R8_SPI0_FIFO_COUNT != 0u) {
        (void)R8_SPI0_FIFO;
    }

    for (i = 0u; i < len; ++i) {
        s_spi_tx_buf[i] = buf[i];
    }
    s_spi_tx_len = (uint16_t)len;
    s_spi_tx_pos = 0u;
    spi_tx_fill_fifo();
    s_spi_tx_pending = true;
    s_spi_tx_start_us = platform_now_us();
    return true;
}

void platform_clock_init(void)
{
    /*
     * Keep system clock setup aligned with SDK helpers so GetSysClock()
     * matches the actual running clock (UART baud depends on it).
     */
    SetSysClock(SYSCLK_FREQ);
}

void platform_gpio_init(void)
{
    GPIOPinRemap(ENABLE, RB_PIN_SPI0);
    GPIOADigitalCfg(ENABLE, (uint16_t)0xFFFFu);
    GPIOBDigitalCfg(ENABLE, SPI_PINS | SPI_IRQ_PIN);

    GPIOB_ModeCfg(SPI_IRQ_PIN, GPIO_ModeOut_PP_5mA);
    GPIOB_ResetBits(SPI_IRQ_PIN);

    /*
     * SPI0 slave IO mode:
     * - CS/SCK/MOSI input pull-up
     * - MISO push-pull output
     * The SPI peripheral owns these pins after SPI0_SlaveInit().
     */
    GPIOB_ModeCfg(GPIO_Pin_12 | GPIO_Pin_13 | GPIO_Pin_14, GPIO_ModeIN_PU);
    GPIOB_ModeCfg(GPIO_Pin_15, GPIO_ModeOut_PP_5mA);
}

void platform_timer_init(void)
{
    s_now_us = 0u;

    TMR0_TimerInit(TMR0_PERIOD_10US);
    TMR0_ClearITFlag(TMR0_3_IT_CYC_END);
    TMR0_ITCfg(ENABLE, TMR0_3_IT_CYC_END);
}

void platform_spi_init(void)
{
    SPI0_SlaveInit();
    /* Default to RX direction so first host command can be captured. */
    R8_SPI0_CTRL_MOD |= RB_SPI_FIFO_DIR;
    s_spi_tx_pending = false;
    s_spi_tx_start_us = 0u;
    s_spi_tx_len = 0u;
    s_spi_tx_pos = 0u;
}

uint32_t platform_now_us(void)
{
    while (TMR0_GetITFlag(TMR0_3_IT_CYC_END)) {
        TMR0_ClearITFlag(TMR0_3_IT_CYC_END);
        s_now_us += US_TICK_STEP;
    }
    return s_now_us;
}

void platform_irq_line_set(bool asserted)
{
    if (asserted) {
        GPIOB_SetBits(SPI_IRQ_PIN);
    } else {
        GPIOB_ResetBits(SPI_IRQ_PIN);
    }
}

void platform_idle(void)
{
    /* Stub: optional low power entry can be inserted here. */
}

/* Timer tick is polled in platform_now_us() to avoid IRQ-induced reset loops during bring-up. */
