"use strict";
// Offline only. No device access or service publication.
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const codec = require("../common/xora-resource-codec.cjs");
const root = path.join(__dirname, "..");
function compile(source) {
  const b = codec.encode(source);
  b.set(crypto.createHash("sha256").update(codec.digestInput(b)).digest(), 32);
  codec.decode(b);
  return b;
}
function generate() {
  const dir = path.join(root, "resources", "xora");
  const files = fs
    .readdirSync(dir)
    .filter((n) => n.endsWith(".xora-resource.json"))
    .sort();
  const lights = [];
  for (const file of files) {
    const source = JSON.parse(fs.readFileSync(path.join(dir, file), "utf8"));
    const bytes = compile(source);
    fs.writeFileSync(path.join(dir, file.replace(/\.json$/, "")), bytes);
    if (source.type !== "switch-mapping") lights.push({ source, bytes });
  }
  fs.writeFileSync(
    path.join(root, "common", "xora-factory-sources.json"),
    JSON.stringify(
      lights.map((x) => x.source),
      null,
      2,
    ) + "\n",
  );
  let header =
    "// Generated by tools/compile_xora_resources.cjs. Edit resources/xora/*.json.\n#pragma once\n#include <stdint.h>\nnamespace XoraResource {\n";
  lights.forEach(({ bytes }, i) => {
    header += `static const uint8_t factory_${i}[] = {${Array.from(bytes).join(",")}};\n`;
  });
  header +=
    "struct FactoryEntry { const uint8_t* bytes; uint16_t size; const char* name; };\nstatic const FactoryEntry factory[] = {\n";
  lights.forEach(({ source, bytes }, i) => {
    header += `{factory_${i},${bytes.length},${JSON.stringify(source.name)}},\n`;
  });
  header +=
    "};\nconstexpr unsigned factoryCount = sizeof(factory)/sizeof(factory[0]);\n}\n";
  fs.writeFileSync(
    path.join(root, "common", "xora_factory_resources.hpp"),
    header,
  );
  console.log(
    `Compiled ${files.length} resources; ${lights.length} factory lighting resources.`,
  );
}
if (require.main === module) {
  if (process.argv[2]) {
    const source = JSON.parse(fs.readFileSync(process.argv[2], "utf8"));
    const output = process.argv[3] || process.argv[2].replace(/\.json$/, "");
    if (output === process.argv[2])
      throw new Error("Choose a separate output path");
    fs.writeFileSync(output, compile(source));
    console.log(output);
  } else generate();
}
module.exports = { compile };
